export const keyQuestions = [
    {'🙈': 'What is an embarrassing childhood memory?'},
    {'𝍐': "What is the most awkward sex you've ever had?"},
    {'💩': "Describe in intimate detail the last time you peed or shat on yourself."},
    {'🧧': "What's the best gift you've ever given someone?"},
    {'👯‍♂️': "Do a 30 sec lapdance. Choose any song."},
    {'🐛': "Drop and do the worm 3 times."},
    {'👏': "What is something you're extremely proud of?"},
    {'🔥': "Choose someone. Work your best/worst pickup line."},
    {'🍆': "What is your favorite porn genre?"},
    {'💘': "Text a family member or a friend that you love them."},
    {'💔': "Text an ex sup."},
    {'🧒': "Describe a fond childhood memory."},
    {'📺': "If your life was a tv show, what genre would it be?"},
    {'🍖': "Who in the room is the freshest meat? Whoever is wrong, take a shot. If you're right, they take a shot."},
    {'🌞': "Describe your perfect day."},
    {'🍻': "Describe your wildest drug experience - alcohol counts!"},
    {'𝇊': "Rate the sensitivity of your nipples from a scale of 1 to 10."},
    {'💋': "Do you remember your first kiss? If so, describe it. If not, describe your last kiss. If you haven't kissed, drink."},
    {'🎤': "Which reality tv show would you want to be on?"},
    {'👍': "Give a compliment to someone in this room - but it has to be one they've never heard before."},
    {'👵': "What is your favorite 'old person' activity?"},
    {'🙀': "What's your best scar or hospitalization story?"},
    {'😱': "Scream like a little bitch."},
    {'🛌': "What did your last partner sound like in bed? If you haven't had any partners what would you sound like in bed?"},
    {'🏛': "If you had to teach a class to 10 year olds, what would you teach?"},
    {'🎗': "If you had to start a charity, what would it be?"},
    {'💵': "If you got 10 million dollars, what would you buy first?"},
    {'🏡': "Would you rather walk into your parents or have they walk into you during the act?"},
    {'🧸': "How many toys do you own? Include all toys into one number."},
    {'👾': "Do you ever feel imposter syndrome? How so?"},
    {'🧟‍♀️': "The zombie apocalypse will start tomorrow (probably from the Tenderloin in SF). What do you do?"},
    {'🤞': "Would you rather have dicks for fingers or fingers for dicks?"},
    {'🥄': "Eat something in the most sensual way possible."},
    {'🦯': "Stay blindfolded for a round."},
    {'📖': "What movie, show, or book traumatized you?"},
    {'👩‍❤️‍💋‍👩': "Have you ever dated or hooked up with a close friend? How did it go?"},
    {'✨': "Have you ever faked an orgasm with your current or last partner? If you've had no partners, fake an orgasm right now (or do it for fun)."},
    {'😢': "Have you ever deeply disappointed someone? What happened?"},
    {'🏢': "If you could make up a holiday, what holiday would it be?"},
    {'🛳': "Choose someone to re-enact a famous movie scene. If you can't think of one, do the Titanic hold for as long as you can."},
    {'🌴': "What dating advice would you give your younger self?"},
    {'🤑': "What was your worst impulsive financial decision?"},
    {'🚽': "What’s the longest you’ve ever spent on the toilet? Why?"},
    {'😇': "What was your earliest recollection of happiness?"},
    {'📞': "Go to your phone usage history. Outside of utilities, which 5 apps do you spend the most time on?"},
    {'👩‍🔬': "Describe the best mentor or coworker you've ever had."},
    {'🧘‍♂️': "What's something you've always wanted to work on on yourself? Have you done it? Why or why not?"},
    {'🔪': "Kiss, Mary, Kill. Donald Trump, Vladimir Putin, Kim Jong-Un."},
    {'🐠': "Kiss, Mary, Kill. Mrs. Potato Head, Dory, Olaf (snowman from Frozen)"},
    {'🐺': "Howl like a pack of wolves at the moon"},
    {'🐣': "Do an interpretive dance of human life."},
    {'⛏': "Choose someone. Work your best pick-up line."},
    {'🦀': "Do a crab walk around everyone 3 times."},
    {'🍔': "Call Mcdonald’s and ask if they sell Whoppers. Put on speaker."},
    {'⁇': "Do you have a 'what if' person? If you're single and not with them right now, text them."},
    {'🔮': "Did you ever correctly predict the future?"},
    {'💊': "What is your recreational substance of choice? Anything you want to try?"},
    {'🧸': "Describe a nostalgic childhood memory."},
    {'🔔': "Describe a time you were late to something important..."},
    {'🤦🏻‍♀️': "Was there someone you regret losing touch with? What's stopping you from reconnecting?"},
    {'🎟': "What's your favorite performance you've attended? Been part of?"},
    {'❔': "Based on your appearance, what's a stereotype about you that's accurate?"},
    {'🏈': "Choose someone. Crumple some paper or napkin. FINGER FOOTBALLLLLL"},
    {'👎': "Never have I ever - but first to 3 wins instead of loses."},
    {'🤢': "What's the worst case of food poisoning you've ever had?"},
    {'↩️': "Choose a victim and ask anything."},
    {'🤑': "How did you make the first $5 you ever made (other than parents)?"},
    {'🌭': "Hot take: a hot dog is a sandwich."},
    {'👛': "Can people truly change? Have you seen it yourself?"},
    {'🥓': "Hot take: **** breakfast."},
    {'😍': "If something awesome happened, who's the first person you would tell?"},
    {'😭': "What's the most recent thing that made you cry?"},
    {'💥': "What fictional character would you bang?"},
    {'😤': "Are you currently holding a grudge against anyone or anything?"},
    {'🎇': "What would you like to accomplish before the year is over?"},
    {'😨': "What is a fear you've faced and how did you face it?"},
    {'🤔': "What is something you fantasize about often?"},
    {'🌚': "What keeps you up at night?"},
    {'🤮': "Describe a recent ick moment about something or someone."},
    {'🐦': "On an average day, how many pigeons do you think you could reasonably carry?"},
    {'🥳': "What are you proud of, but never have an excuse to talk about"},
    {'🐊': "If all animals were the same size, what would win in a fight?"},
    {'🍕': "If you were a pizza topping what would you be and why?"},
    {'🌎': "In what ways do you not benefit the world?"},
    {'🦡': "What is something you're bad at, no matter how hard you try?"},
    {'🏔': "What immediately makes you think more highly of someone?"},
    {'🦜': "If you could train a pigeon to poop on someone, who would you choose?"},
    {'👨‍🎤': "Wink at someone while singing Baby by Bieber."},
    {'🎤': "Choose someone. Sing a Disney duet."}
];